/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StartImport } from './routes/start'
import { Route as LoginImport } from './routes/login'
import { Route as AdoptionImport } from './routes/adoption'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StartRoute = StartImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AdoptionRoute = AdoptionImport.update({
  id: '/adoption',
  path: '/adoption',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/adoption': {
      id: '/adoption'
      path: '/adoption'
      fullPath: '/adoption'
      preLoaderRoute: typeof AdoptionImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adoption': typeof AdoptionRoute
  '/login': typeof LoginRoute
  '/start': typeof StartRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adoption': typeof AdoptionRoute
  '/login': typeof LoginRoute
  '/start': typeof StartRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/adoption': typeof AdoptionRoute
  '/login': typeof LoginRoute
  '/start': typeof StartRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adoption' | '/login' | '/start'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adoption' | '/login' | '/start'
  id: '__root__' | '/' | '/adoption' | '/login' | '/start'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdoptionRoute: typeof AdoptionRoute
  LoginRoute: typeof LoginRoute
  StartRoute: typeof StartRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdoptionRoute: AdoptionRoute,
  LoginRoute: LoginRoute,
  StartRoute: StartRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/adoption",
        "/login",
        "/start"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/adoption": {
      "filePath": "adoption.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/start": {
      "filePath": "start.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
